---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-server
  name: admin-server
  namespace: spring-petclinic
spec:
  ports:
  - name: "http"
    port: 9090
    targetPort: 9090
    nodePort: 31301
  selector:
    app: admin-server
  type: NodePort