---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka
  name: eureka
  namespace: spring-petclinic
spec:
  ports:
  - name: "http"
    port: 8761
    targetPort: 8761
    nodePort: 31201
  selector:
    app: eureka
  type: NodePort