---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-server
  name: config-server
  namespace: spring-petclinic
spec:
  ports:
  - name: "http"
    port: 8888
    # appProtocol: "http"
    targetPort: 8888
  selector:
    app: config-server
status:
  loadBalancer: {}